//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.25 at 03:18:58 PM EDT 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ElementaryQuestion complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ElementaryQuestion">
 *   &lt;complexContent>
 *     &lt;extension base="{}Question">
 *       &lt;sequence>
 *         &lt;element name="Hint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author JDOM Library
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementaryQuestion", propOrder = { "hint" })
public class ElementaryQuestion extends Question {

	/** String representing the hint for an ElementaryQuestion */
	@XmlElement(name = "Hint", required = true)
	protected String hint;

	/**
	 * Gets the value of the hint property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHint() {
		return hint;
	}

	/**
	 * Sets the value of the hint property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHint(String value) {
		this.hint = value;
	}

}
