//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.25 at 03:18:58 PM EDT 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Question complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Question" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChoiceA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChoiceB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChoiceC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChoiceD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Answer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author JDOM Library
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Question", propOrder = { "question", "choiceA", "choiceB",
		"choiceC", "choiceD", "answer" })
@XmlSeeAlso({ ElementaryQuestion.class, AdvancedQuestion.class,
		StandardQuestion.class })
public class Question {

	/** String representing the question */
	@XmlElement(name = "Question", required = true)
	protected String question;
	/** String representing choice A */
	@XmlElement(name = "ChoiceA", required = true)
	protected String choiceA;
	/** String representing choice B */
	@XmlElement(name = "ChoiceB", required = true)
	protected String choiceB;
	/** String representing choice C */
	@XmlElement(name = "ChoiceC", required = true)
	protected String choiceC;
	/** String representing choice D */
	@XmlElement(name = "ChoiceD", required = true)
	protected String choiceD;
	/** String representing the answer choice */
	@XmlElement(name = "Answer", required = true)
	protected String answer;

	/**
	 * Gets the value of the question property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * Sets the value of the question property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setQuestion(String value) {
		this.question = value;
	}

	/**
	 * Gets the value of the choiceA property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChoiceA() {
		return choiceA;
	}

	/**
	 * Sets the value of the choiceA property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChoiceA(String value) {
		this.choiceA = value;
	}

	/**
	 * Gets the value of the choiceB property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChoiceB() {
		return choiceB;
	}

	/**
	 * Sets the value of the choiceB property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChoiceB(String value) {
		this.choiceB = value;
	}

	/**
	 * Gets the value of the choiceC property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChoiceC() {
		return choiceC;
	}

	/**
	 * Sets the value of the choiceC property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChoiceC(String value) {
		this.choiceC = value;
	}

	/**
	 * Gets the value of the choiceD property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChoiceD() {
		return choiceD;
	}

	/**
	 * Sets the value of the choiceD property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChoiceD(String value) {
		this.choiceD = value;
	}

	/**
	 * Gets the value of the answer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * Sets the value of the answer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAnswer(String value) {
		this.answer = value;
	}

}
